#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo "Checking commit"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonstandard=$(git config --bool hooks.allownonstandard)


# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonstandard" != "true" ]; then
	rubocop -R `git diff --cached --name-only $against`
	if [ "$?" != "0" ]; then
		cat <<\EOF
		Error: Failed code verification against rubocop standards

		This can cause problems if you want to work with people

		To be polite and cool in the office, please accept our code policy

		If you know what you are doing you can disable this check using:

		git config hooks.allownonstandard true
EOF
		exit 1
	fi
fi

