#!/usr/bin/env ruby
branch_name=`git symbolic-ref -q HEAD`
branch_name = branch_name.gsub('refs/heads/', '').strip
changed_files = `git diff --name-only #{ARGV[0]}/#{branch_name}`.split("\n").map(&:strip).select{|n| n =~ /\.rb$/}
#run the file specific test
test_files = changed_files.map do |name|
  if name =~ /^app/
    name.gsub('app/', 'test/').gsub(/\.rb$/, '_test.rb')
  elsif name =~ /^test/
    name
  else
    nil
  end
end.reject(&:nil?).uniq
#abort if there is a test missing
unless test_files.reject{ |n| File.exist?(n) }.empty?
  puts %Q{
      Aborting push because there are missing test files: #{test_files.reject{ |n| File.exist?(n) }}
  }
  exit 1
end
#if there are config files changes, run all tests
unless changed_files.select{ |n| n =~ /^config/ }.empty?
  test_files = ''
end
system('git stash')
result = system("rails test #{test_files.join(' ')}")
system('git stash apply')
unless result
  puts %Q{
    Aborting push due to failed tests
  }
  exit 1
end
